[git_hook] Fix coding standards and add fixers

diff --git a/scripts/git-hooks/pre-commit b/scripts/git-hooks/pre-commit
--- a/scripts/git-hooks/pre-commit
+++ b/scripts/git-hooks/pre-commit
@@ -6,6 +6,8 @@ TMP_STAGING=".staging"
 
 rm -rf $TMP_STAGING
 
+printf "Running Linter\n"
+
 while read FILE; do
 if [[ -f $FILE ]]; then
     mkdir -p "$TMP_STAGING/$(dirname $FILE)"
@@ -23,6 +25,8 @@ if [[ $EXIT_CODE -eq 1 ]];then
   printf "\e[1;31m\tAborting commit due to syntax errors in staged files.\e[0m\n" >&2;
   exit 1
 fi
+
+printf "\e[1;92m\tNo syntax error found.\e[0m\n" >&2;
 
 printf "Validating Coding Standards\n"
 
