[wercker] Allow only canary branch on canary pipeline

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -80,7 +80,11 @@ deploy:
           name: Check if canary branch is up-to-date
           code: |
             MASTER=$(git rev-parse master)
-            if [ "$RZP_WERCKER_CURR_PIPELINE_ID" = "$RZP_WERCKER_CANARY_PIPELINE_ID" ]; then
+            if [ "$RZP_WERCKER_CURR_PIPELINE_ID" == "$RZP_WERCKER_CANARY_PIPELINE_ID" ]; then
+              if [ "$WERCKER_GIT_BRANCH" != "canary" ]; then
+                echo "[ERROR] Cannot deploy a non-canary branch to canary instance"
+                exit $?
+              fi
               if [ -n $(git rev-list HEAD | grep $MASTER) ]; then
                 echo "[ERROR] Cannot deploy outdated branch to canary"
                 exit $?
