[wercker] Allow only updated branch on canary pipeline

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -77,6 +77,16 @@ deploy:
               fi
             fi
       - script:
+          name: Check if canary branch is up-to-date
+          code: |
+            MASTER=$(git rev-parse master)
+            if [ "$RZP_WERCKER_CURR_PIPELINE_ID" = "$RZP_WERCKER_CANARY_PIPELINE_ID" ]; then
+              if [ -n $(git rev-list HEAD | grep $MASTER) ]; then
+                echo "[ERROR] Cannot deploy outdated branch to canary"
+                exit $?
+              fi
+            fi
+      - script:
           name: List directory
           code: ls -lah
       - script:
